### ISSUE TITLE
Path issue for vignettes/report.latex in vignettes/demo.Rmd

### ISSUE THREAD

**Issue by tompollard** [CC-HIC/ccanonym#24]
Running knitr on [vignettes/demo.Rmd](https://github.com/CC-HIC/ccanonym/blob/master/vignettes/demo.Rmd) in RStudio fails with the following error:

```R
pandoc: vignettes/report.latex: openFile: does not exist (No such file or directory)
```

Changing the path to vignettes/report.latex in the header fixes this issue for me:

```yaml
output: 
  pdf_document:
    include: 
      in_header: report.latex
```
