### ISSUE TITLE
Meaning of NIHR_HIC_ICU_0097 = L in test_data_anonym.xml

### ISSUE THREAD

**Issue by tompollard** [CC-HIC/ccanonym#30]
The [test_data_anonym.xml](https://github.com/CC-HIC/ccanonym/blob/master/tests/data/test_data_anonym.xml) file includes the following entry:

```xml
<d:NIHR_HIC_ICU_0097>L</d:NIHR_HIC_ICU_0097>
```

What is 'L' in this case and what is the expected behaviour of the anonymisation function? 

The following file suggests 3 possible values for this field (A, D, E): https://github.com/CC-HIC/ccdata/blob/master/tests/data/test_analysis_ref.yaml

```yaml
NIHR_HIC_ICU_0097:
  shortName: dead_icu
  dataItem: Dead or alive on discharge
  distribution: binary
  category:
    levels:
      A: Alive
      D: Dead
      E: Alive - not discharged
    apply: drop_entry
```
